CREATE TABLE IF NOT EXISTS SALESMAN (
    SALESMAN_ID TEXT PRIMARY KEY,
    NAME TEXT,
    CITY TEXT,
    COMISSION REAL
);

INSERT INTO SALESMAN (SALESMAN_ID, NAME, CITY, COMISSION) VALUES
    ('5001', 'JAMES HOOG', 'NEW YORK', 0.15),
    ('5002', 'NAIL KNITE', 'PARIS', 0.13),
    ('5005', 'PIT ALEX', 'LONDON', 0.11),
    ('5006', 'MC LYON', 'PARIS', 0.14),
    ('5007', 'PAUL ADAM', 'ROME', 0.13),
    ('5003', 'LAUSON HEN', 'SAN JOSE', 0.12);

SELECT * FROM SALESMAN;